Ansible playbooks for prometheus, grafana,sensu
0KnowledgeNetwork/katzenpost-ansible pull request #1
Opened 2024-04-08 18:21 UTC by amitbasuri

2024-04-08 20:23 UTC, david415 requested changes
Looks great! There's just a few minor things to fix.

2024-04-08 20:23 UTC, david415 commented on ansible/playbooks/setup_sensu.yml
> +    sensu_admin_password: "P@ssw0rd!"
can we use an encrypted vault of some sort to handle passwords such that we aren't publish passwords in plaintext in the git repo?

2024-04-08 20:23 UTC, david415 commented on ansible/run_playbook.sh
> +#rm -rf playbooks/artifacts
remove section instead of commenting it out.

2024-04-08 20:23 UTC, david415 commented on ansible/run_playbook.sh
> +        #Password: P@ssw0rd!
no passwords in git

2024-04-08 20:23 UTC, david415 commented on ansible/setup_monitoring.sh
> +#ansible-galaxy collection install prometheus.prometheus --force
remove uncommented section or justify it's existence

2024-04-08 20:23 UTC, david415 commented on ansible/setup_monitoring.sh
> +#grafana
remove uncommented section or explain why it should exist

2024-04-08 20:23 UTC, david415 commented on ansible/setup_monitoring.sh
> +#Username: admin Password: admin
no passwords in git

2024-04-08 20:24 UTC, david415 commented on ansible/infra/sg.tf
> +    from_port   = 22
Can we setup sshd to listen on a random high port instead of 22? such as 33429

2024-04-08 20:27 UTC, david415 commented
We want a publicly accessible URL that we can use to navigate to the grafana prometheus dashboard AND the sensu status page. However we want this to be private... which i think means htdigest password protection

2024-04-10 04:43 UTC, xendarboh commented on ansible/playbooks/deploy_mixnet.yml
> +    - node_exporter
```
ERROR! the role 'node_exporter' was not found in /home/.../ansible/playbooks/roles:/home/user/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/.../ansible/playbooks

The error appears to be in '/home/.../ansible/playbooks/deploy_mixnet.yml': line 17, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - chrony
    - node_exporter
      ^ here
```

2024-04-10 07:11 UTC, amitbasuri commented on ansible/playbooks/deploy_mixnet.yml
> +    - node_exporter
@xendarboh updated the code, we don't need this, we will use setup_prometheus.yml to setup node exporter.

2024-04-10 12:16 UTC, amitbasuri commented on ansible/infra/sg.tf
> +    from_port   = 22
@david415 yes should be possible, how about doing this in a different PR?

2024-04-10 12:18 UTC, amitbasuri commented on ansible/playbooks/deploy_mixnet.yml
> +    - node_exporter
plz check new README for usage

2024-04-10 12:27 UTC, amitbasuri commented
> We want a publicly accessible URL that we can use to navigate to the grafana prometheus dashboard AND the sensu status page. However we want this to be private... which i think means htdigest password protection

sure, how about doing this as part of a different PR, also added README for better usage.

2024-04-10 19:56 UTC, david415 commented on ansible/run_playbook.sh
> +#rm -rf playbooks/artifacts
Please please please please please remove commented out section of code.

2024-04-10 19:56 UTC, david415 commented on ansible/run_playbook.sh
> +#sudo apt-get update
remove section of commented out code. this is what git is for.

2024-04-10 20:14 UTC, amitbasuri commented on ansible/run_playbook.sh
> +#sudo apt-get update
removed

2024-04-12 19:42 UTC, david415 commented on ansible/infra/sg.tf
> +    from_port   = 22
ok

2024-04-12 19:45 UTC, david415 approved these changes

2024-04-12 22:01 UTC, xendarboh approved these changes

2024-04-12 22:09 UTC, merged